<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<title>Embedded Example</title>
<meta http-equiv="Content-type" content="text/html; charset=iso-8859-1" />
<meta name="description" content="An example of a page embedding a summary from Dejal Simon." />
<meta name="author" content="David Sinclair, Dejal Systems, LLC" />
<link rel="stylesheet" href="./embedded/resources/default.css" type="text/css" media="all" />
</head>
<body>

<h1>Embedded Example</h1>

<p>The following summary table is included from a separate file.  That file is generated by <a href="http://www.dejal.com/simon/">Dejal Simon</a>, and can be included in here without having to modify this file.  You only need to edit this sample file to specify the relative path to the summary.inc file (it is './embedded/summary.inc' by default).</p>

<?php include('./embedded/summary.inc'); ?>

<p>This is some text at the end of the main document.</p>

</body>
</html>
